### PR TITLE
Updating lodash

### PR DESCRIPTION
**Pull request by jeffswartz**
There's a security alert on lodash 3.2.0.

### CODE REVIEW

**Comment by msach22** [comment]
@jeffswartz Should we add a package lock file so as well?

**Comment by jeffswartz** [comment]
@msach22 I was wondering about that, too. I could add my package-lock.json file. wdyt?

**Comment by inlightmedia** [comment]
Thanks for fixing this!

**Review by inlightmedia — APPROVED** [review]
Thanks for addressing this security issue!

**Review by msach22 — APPROVED** [review]
LGTM

**Pull request merged**
